// <auto-generated />
using System;
using ApplyLog.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplyLog.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250409105241_MakeDeadlineNotNullable")]
    partial class MakeDeadlineNotNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("ApplyLog.Models.Bewerbung", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("applicationlink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("firmaID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("gehalt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("homeoffice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("jobort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("result")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("whenapplied")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("firmaID");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("ApplyLog.Models.Firma", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Kontaktid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ort")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("Kontaktid");

                    b.ToTable("Firma");
                });

            modelBuilder.Entity("ApplyLog.Models.Kontakt", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("number")
                        .HasColumnType("TEXT");

                    b.Property<string>("website")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Kontakt");
                });

            modelBuilder.Entity("ApplyLog.Models.TODO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Describtion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PriorityLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("ApplyLog.Models.Bewerbung", b =>
                {
                    b.HasOne("ApplyLog.Models.Firma", "firma")
                        .WithMany()
                        .HasForeignKey("firmaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("firma");
                });

            modelBuilder.Entity("ApplyLog.Models.Firma", b =>
                {
                    b.HasOne("ApplyLog.Models.Kontakt", "Kontakt")
                        .WithMany()
                        .HasForeignKey("Kontaktid");

                    b.Navigation("Kontakt");
                });
#pragma warning restore 612, 618
        }
    }
}
